name: Publish on Tag

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0.0, v2.3.4, etc.

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          scope: '@shibaone'  # Replace with your username/org

      - name: Configure .npmrc for GitHub Packages
        run: |
          echo "@your-username:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PAT }}" >> ~/.npmrc

      - name: Install dependencies
        run: npm install

      - name: Build the package
        run: npm run build

      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PAT }}
        run: npm publish --access restricted
